inv-name: "§cBazard"
auto-save: true #if the auto save of the items in the bazard at each update
message-time: 600 #time in second while the message of tha add of a new item can be sent, put -1 to disable it